gatling {
  charting {
    indicators {
      lowerBound = 1
      higherBound = 5
      # percentile1 and percentile2 are used for the detailed HTML report, not the console summary buckets.
      percentile1 = 75
      percentile2 = 95
    }
  }
  console {
    light = true
  }
}
