# Default values for snowflake-id-service
replicaCount: 3

image:
  repository: "snowflake-id-service"
  pullPolicy: Never
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: false

podAnnotations: {}

podSecurityContext:
  fsGroup: 65532
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  type: NodePort
  port: 9090
  targetPort: 9090
  nodePort: 30090

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - localhost
      secretName: snowflake-id-service-tls

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 320Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - snowflake-id-service
          topologyKey: "kubernetes.io/hostname"

# Application specific configuration
app:
  port: 9090
  healthPort: 9091
  metricsPort: 8080
  name: snowflake-id-service

# Extra environment variables to inject into the pods
extraEnv: []
# Example:
#extraEnv:
#  - name: LOGGING_LEVEL_COM_YMOROZ_SNOWFLAKE
#    value: DEBUG

observability:
  metricsService:
    enabled: true
    port: 8080
  prometheus:
    serviceMonitor:
      enabled: true
      interval: 15s
      scrapeTimeout: 10s
      path: /actuator/prometheus
      labels:
        release: kube-prometheus-stack

# Persistence configuration
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Mi
  storageClassName: "" # Use default storage class

pdb:
  enabled: true
  minAvailable: 1

# Health checks
livenessProbe:
  grpc:
    port: 9091
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  grpc:
    port: 9091
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
