deploymentMode: SingleBinary

memberlist:
  service:
    publishNotReadyAddresses: true

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 3
  storage:
    type: s3
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 168h
  compactor:
    retention_enabled: true
    delete_request_store: s3
  ruler:
    enable_api: true

singleBinary:
  replicas: 3
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

chunksCache:
  enabled: false

resultsCache:
  enabled: false

minio:
  enabled: true

lokiCanary:
  enabled: false

test:
  enabled: false
