{{- if .Values.observability.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snowflake-id-service.fullname" . }}-metrics
  labels:
    {{- include "snowflake-id-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.observability.metricsService.port }}
      targetPort: {{ .Values.app.metricsPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "snowflake-id-service.selectorLabels" . | nindent 4 }}
{{- end }}
